# Generated by Django 5.1.4 on 2025-01-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("live_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="livemeasurements",
            table="LiveMonitoring",
        ),
    ]
