# Generated by Django 5.1.4 on 2025-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_monitoring", "0002_alter_livemeasurements_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveMonitoring",
            fields=[
                ("pc_date", models.TextField()),
                ("pc_time", models.TextField()),
                (
                    "unix_time",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("meter_date", models.TextField()),
                ("meter_time", models.TextField()),
                ("LAeq", models.FloatField()),
                ("response_time", models.FloatField()),
            ],
            options={
                "db_table": "LiveMonitoring",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="LiveMeasurements",
        ),
    ]
