// This is the only file you need to include
// Auto-Generated on 9/7/2023


#ifndef LD_TRANSLATOR

#include <map>
#include <vector>
#include <string>
#include <ApiHeader.h>
#include <StringWrapper.h>
#include <CSlmRecord.h>
#include <CLDRecordBase.h>
#include <CReactiveObservableBase.h>
#include <CReactiveObject.h>
#include <IReactiveObject.h>
#include <IEnableLogger.h>
#include <CPropertyChangingEventArgs.h>
#include <CEventArgs.h>
#include <IReactiveNotifyPropertyChanged_IReactiveObject.h>
#include <IReactivePropertyChangedEventArgs_IReactiveObject.h>
#include <IObservable_IReactivePropertyChangedEventArgs_IReactiveObject.h>
#include <IObserver_IReactivePropertyChangedEventArgs_IReactiveObject.h>
#include <IHandleObservableErrors.h>
#include <IActivatableReactiveObject.h>
#include <IActivatableViewModel.h>
#include <CViewModelActivator.h>
#include <SUnit.h>
#include <IObservable_SUnit.h>
#include <IObserver_SUnit.h>
#include <ICleanup.h>
#include <ILDRecord.h>
#include <CCalibration.h>
#include <SDateTime.h>
#include <IConvertible.h>
#include <STimeSpan.h>
#include <Array_StringWrapper.h>
#include <CArray.h>
#include <IList.h>
#include <Array_int32_t.h>
#include <IList_int32_t.h>
#include <Array_int64_t.h>
#include <IList_int64_t.h>
#include <IComparer.h>
#include <IList_StringWrapper.h>
#include <SCalData2_t.h>
#include <ISupportByteArrayConversion.h>
#include <Array_float.h>
#include <IList_float.h>
#include <SPTBInfo_t.h>
#include <ISlmRecord.h>
#include <CMetaDataRecord.h>
#include <IMetaDataRecord.h>
#include <IGeneralMetaBlock.h>
#include <IMetaBlock.h>
#include <CGeneralInfo.h>
#include <IGeneralInfo.h>
#include <IEditBandMetaBlock.h>
#include <CEditBandInfo.h>
#include <IEditBandInfo.h>
#include <SortedList_int32_t_CEditBandInfo.h>
#include <IDictionary_int32_t_CEditBandInfo.h>
#include <IDictionary.h>
#include <IComparer_int32_t.h>
#include <IList_CEditBandInfo.h>
#include <IChartMetaBlock.h>
#include <CChartInfo.h>
#include <IChartInfo.h>
#include <IList_CChartInfo.h>
#include <ICommentMetaBlock.h>
#include <CMarkerInfo.h>
#include <IMarkerInfo.h>
#include <List_CMarkerInfo.h>
#include <IList_CMarkerInfo.h>
#include <IComparer_CMarkerInfo.h>
#include <Array_CMarkerInfo.h>
#include <IRt60DecayMetaBlock.h>
#include <CRt60DecayInfo.h>
#include <IRt60DecayInfo.h>
#include <List_CRt60DecayInfo.h>
#include <IList_CRt60DecayInfo.h>
#include <IComparer_CRt60DecayInfo.h>
#include <Array_CRt60DecayInfo.h>
#include <CSoundRecordMetaBlock.h>
#include <ISoundRecordMetaBlock.h>
#include <CSoundRecordInfo.h>
#include <CMetaBlockInfo.h>
#include <IMetaBlockInfo.h>
#include <ISoundRecordInfo.h>
#include <IList_CSoundRecordInfo.h>
#include <CManifestMetaBlock.h>
#include <IManifestMetaBlock.h>
#include <IList_CMetaBlockInfo.h>
#include <ILDRecordWithMetaRecord_CMetaDataRecord.h>
#include <CMeasureRt60.h>
#include <CMeasureBase.h>
#include <SRt60ByTime_t.h>
#include <SRt60TimeSample_t.h>
#include <Array_SRt60TimeSample_t.h>
#include <IList_SRt60TimeSample_t.h>
#include <SRt60DataLimits_t.h>
#include <Array_SRt60DataLimits_t.h>
#include <IList_SRt60DataLimits_t.h>
#include <SRt60CalcLines_t.h>
#include <SRt60Record_t.h>
#include <SRt60Average_t.h>
#include <SRaHeader_t.h>
#include <SRt60Sample_t.h>
#include <SRt60SampleData_t.h>
#include <Array_SRt60SampleData_t.h>
#include <IList_SRt60SampleData_t.h>
#include <Array_uint8_t.h>
#include <IList_uint8_t.h>
#include <SRt60SampleLimits_t.h>
#include <SDataLimitsEDT_t.h>
#include <Array_SDataLimitsEDT_t.h>
#include <IList_SDataLimitsEDT_t.h>
#include <SRt60Data_t.h>
#include <Array_int32_t_2.h>
#include <SRT60_QI_t.h>
#include <CEventInfo.h>
#include <CEventTimeHistoryManager.h>
#include <SEventTHRecord_t.h>
#include <SEventTHWind_t.h>
#include <Array_SEventTHRecord_t.h>
#include <IList_SEventTHRecord_t.h>
#include <SEventTriggerInfo_t.h>
#include <SEventLevelInfo_t.h>
#include <SEventWeatherInfo_t.h>
#include <SWeatherData_t.h>
#include <Array_uint32_t.h>
#include <IList_uint32_t.h>
#include <Sslm2.h>
#include <SDetectorTs_t.h>
#include <SLevelTs_t.h>
#include <SDetector_t.h>
#include <SLevel_t.h>
#include <Array_SDetector_t.h>
#include <IList_SDetector_t.h>
#include <SSpectraInfo_t.h>
#include <CTimeHistoryManager.h>
#include <SstTHItemInfo_t.h>
#include <IList_SstTHItemInfo_t.h>
#include <CTimeHistoryRecord.h>
#include <Array_float_2.h>
#include <IList_CTimeHistoryRecord.h>
#include <CTimeHistoryOptions.h>
#include <SstTHOptionInfo_t.h>
#include <Array_SstTHOptionInfo_t.h>
#include <IList_SstTHOptionInfo_t.h>
#include <List_int32_t.h>
#include <ValueTuple_int32_t_StringWrapper.h>
#include <ITuple.h>
#include <List_ValueTuple_int32_t_StringWrapper.h>
#include <IList_ValueTuple_int32_t_StringWrapper.h>
#include <IComparer_ValueTuple_int32_t_StringWrapper.h>
#include <Array_ValueTuple_int32_t_StringWrapper.h>
#include <SUserPreferences_t.h>
#include <Sset_Enum.h>
#include <Sset_UnsignedInt.h>
#include <Sset_Int.h>
#include <Sset_FloatArray11.h>
#include <Sset_FloatArray13.h>
#include <Sset_String.h>
#include <Sset_Float.h>
#include <Array_Sset_Enum.h>
#include <IList_Sset_Enum.h>
#include <Array_Sset_String.h>
#include <IList_Sset_String.h>
#include <CMarineMammalsSummaryData.h>
#include <CMarineMammalsData.h>
#include <List_CMarineMammalsData.h>
#include <IList_CMarineMammalsData.h>
#include <IComparer_CMarineMammalsData.h>
#include <Array_CMarineMammalsData.h>
#include <SSystemSettings_t.h>
#include <SFirwareVersion_t.h>
#include <Array_Sset_Float.h>
#include <IList_Sset_Float.h>
#include <Sset_IPAddr.h>
#include <Sset_ByteString.h>
#include <SSystemMetrics_t.h>
#include <SMetrics_t.h>
#include <IList_CEventInfo.h>
#include <SEnvPreampInfo_t.h>
#include <SEnvPreampData_t.h>
#include <SDoseCriteria_t.h>
#include <Array_SDoseCriteria_t.h>
#include <IList_SDoseCriteria_t.h>
#include <SGps_t.h>
#include <Sdegmin.h>
#include <CIntervalInfo.h>
#include <CMeasureRta.h>
#include <SRtaRecord_t.h>
#include <SOverload_t.h>
#include <SEventCounts_t.h>
#include <Array_SEventCounts_t.h>
#include <IList_SEventCounts_t.h>
#include <IList_CIntervalInfo.h>
#include <CSessionLog.h>
#include <SSessionLog_t.h>
#include <SLoggedData_t.h>
#include <CRunRecord.h>
#include <IList_CRunRecord.h>
#include <CSoundRecord.h>
#include <IList_CSoundRecord.h>
#include <SCalCheckHistory_t.h>
#include <Array_SCalData2_t.h>
#include <IList_SCalData2_t.h>
#include <Array_Array_SCalData2_t.h>
#include <IList_Array_SCalData2_t.h>
#include <SCalHistory2_t.h>
#include <SCalHistoryTypes_t.h>
#include <Array_SCalHistoryTypes_t.h>
#include <IList_SCalHistoryTypes_t.h>
#include <SDailyNoise_t.h>
#include <SEventTriggerConfig_t.h>
#include <IList_SEventTriggerConfig_t.h>
#include <CMeasureFft.h>
#include <SFftRecord_t.h>
#include <SFftInfo_t.h>
#include <SFftLevels_t.h>
#include <SFftTriggerInfo_t.h>
#include <CToneInfo.h>
#include <IList_CToneInfo.h>
#include <IList_CMeasureFft.h>
#include <SSlmLnInfo_t.h>
#include <SMeasControls_t.h>
#include <Sset_TableFloatsLNS.h>
#include <Sset_EnumFloats.h>
#include <Array_Sset_EnumFloats.h>
#include <IList_Sset_EnumFloats.h>
#include <SCalHistory_t.h>
#include <SCalData_t.h>
#include <Array_SCalData_t.h>
#include <IList_SCalData_t.h>
#include <CPartition.h>
#include <CRoomRx.h>
#include <CRoomBase.h>
#include <Array_CMeasureRt60.h>
#include <IList_CMeasureRt60.h>
#include <CRoomTx.h>
#include <IAgencyApprovalInfo.h>
#include <CSpartanRecord.h>
#include <ISpartanRecord.h>
#include <CSpartanMetaRecord.h>
#include <ILDRecordWithMetaRecord_CSpartanMetaRecord.h>
#include <CX21MetricMeta.h>
#include <IList_CX21MetricMeta.h>
#include <CTimeHistoryEntry_t.h>
#include <Nullable_uint32_t.h>
#include <List_float.h>
#include <IComparer_float.h>
#include <List_IConvertible.h>
#include <IList_IConvertible.h>
#include <IComparer_IConvertible.h>
#include <Array_IConvertible.h>
#include <IList_CTimeHistoryEntry_t.h>
#include <SMeasSettingsSpartan_t.h>
#include <SString16_t.h>
#include <Array_wchar_t.h>
#include <IList_wchar_t.h>
#include <SString64_t.h>
#include <SObaData48Bins_t.h>
#include <Array_SDetectorTs_t.h>
#include <IList_SDetectorTs_t.h>
#include <SExcdDataSpartan_t.h>
#include <SExceedanceDataRecordSpartan_t.h>
#include <Array_SExceedanceDataRecordSpartan_t.h>
#include <IList_SExceedanceDataRecordSpartan_t.h>
#include <SLnDataSpartan_t.h>
#include <SOverallDataSpartan_t.h>
#include <STwa_t.h>
#include <Array_STwa_t.h>
#include <IList_STwa_t.h>
#include <CSpartanInterval.h>
#include <SMeasHistSpartan_t.h>
#include <SBlockHeaderSpartan_t.h>
#include <SMeasAnyDataSpartan_t.h>
#include <SOverloadSpartan_t.h>
#include <SOverloadInfo_t.h>
#include <SDetectorTs2_t.h>
#include <Array_SLevelTs_t.h>
#include <IList_SLevelTs_t.h>
#include <Array_SDetectorTs2_t.h>
#include <IList_SDetectorTs2_t.h>
#include <SBlockFooterSpartan_t.h>
#include <Array_int64_t_2.h>
#include <IList_CSpartanInterval.h>
#include <CSpartanSoundRecord.h>
#include <IList_CSpartanSoundRecord.h>
#include <CSessionLogEntry_t.h>
#include <IList_CSessionLogEntry_t.h>
#include <Nullable_float.h>
#include <CJContainer.h>
#include <CJToken.h>
#include <IJsonLineInfo.h>
#include <IDynamicMetaObjectProvider.h>
#include <CJsonSerializer.h>
#include <CJsonSerializerSettings.h>
#include <CJsonConverter.h>
#include <CJsonWriter.h>
#include <Nullable_bool.h>
#include <Nullable_uint8_t.h>
#include <Nullable_wchar_t.h>
#include <Nullable_SDateTime.h>
#include <SDateTimeOffset.h>
#include <Nullable_SDateTimeOffset.h>
#include <Nullable_double.h>
#include <Nullable_int64_t.h>
#include <Nullable_int8_t.h>
#include <Nullable_int16_t.h>
#include <Nullable_STimeSpan.h>
#include <Nullable_uint64_t.h>
#include <Nullable_uint16_t.h>
#include <IList_CJsonConverter.h>
#include <IContractResolver.h>
#include <CJsonContract.h>
#include <CSerializationCallback.h>
#include <IList_CSerializationCallback.h>
#include <CSerializationErrorCallback.h>
#include <CErrorContext.h>
#include <IList_CSerializationErrorCallback.h>
#include <IEqualityComparer.h>
#include <IReferenceResolver.h>
#include <ITraceWriter.h>
#include <CSerializationBinder.h>
#include <ISerializationBinder.h>
#include <CErrorEventArgs.h>
#include <EventHandler_CErrorEventArgs.h>
#include <CTextReader.h>
#include <CJsonConverterCollection.h>
#include <Collection_CJsonConverter.h>
#include <Array_CJsonConverter.h>
#include <CJsonLoadSettings.h>
#include <CJsonSelectSettings.h>
#include <CJsonCloneSettings.h>
#include <IList_CJToken.h>
#include <ITypedList.h>
#include <IBindingList.h>
#include <CJsonMergeSettings.h>
#include <Array_CJToken.h>
#include <SManifestBlockSpartan_t.h>
#include <SFileInfoHeaderSpartan_t.h>
#include <SManifestEntrySpartan_t.h>
#include <SSysSettingsSpartan_t.h>
#include <SString32_t.h>
#include <SString256_t.h>
#include <SModifiedDataSpartan_t.h>
#include <SPrePostCalSpartan_v2_t.h>
#include <SDeviceInfoSpartan_t.h>
#include <CSlmLegacy.h>
#include <CSlmConstants.h>
#include <SRt60ColInfo_t.h>
#include <SGenericLookup_t.h>
#include <Array_SGenericLookup_t.h>
#include <IList_SGenericLookup_t.h>
#include <SGenericLookupFloat_t.h>
#include <Array_SGenericLookupFloat_t.h>
#include <IList_SGenericLookupFloat_t.h>
#include <SFilterFreqInfo_t.h>
#include <Array_SFilterFreqInfo_t.h>
#include <IList_SFilterFreqInfo_t.h>
#include <Array_SRt60ColInfo_t.h>
#include <IList_SRt60ColInfo_t.h>
#include <SRt60ColOrder_t.h>
#include <Array_SRt60ColOrder_t.h>
#include <IList_SRt60ColOrder_t.h>
#include <SIsoGrades_t.h>
#include <Array_SIsoGrades_t.h>
#include <IList_SIsoGrades_t.h>
#include <CSpartanConstants.h>
#include <Array_ESpartanFileBlock.h>
#include <IList_ESpartanFileBlock.h>
#include <CLDConstants.h>
#include <Translator.h>

#endif // LD_TRANSLATOR
